# Generated by Django 6.0.7 on 2026-08-14 10:06

import django.db.models.deletion
from django.db import migrations, models


def move_categories(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Category = apps.get_model("catalog", "Category")

    for product in Product.objects.all():
        old_name = product.category

        if old_name:
            category = Category.objects.filter(name=old_name).first()

            if category is None:
                category = Category.objects.create(name=old_name)

            product.category_new = category
            product.save(update_fields=["category_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
            ),
        ),

        migrations.RunPython(
            move_categories,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name="product",
            name="category",
        ),

        migrations.RenameField(
            model_name="product",
            old_name="category_new",
            new_name="category",
        ),
    ]
