# Generated by Django 6.0.7 on 2026-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
