# Generated by Django 6.0.7 on 2026-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openpage", "0002_alter_post_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
